Update index.js
Erro corrigido:
TypeError: Cannot destructure property 'message' of 'result' as it is null.
Fora do escopo: Mensagem não encontrada!

Alterações feitas:
Adicionado: const TypeFound e tipos.
Agora, senderKeyDistributionMessage e messageContextInfo serão ignorados.